name: Claude Code Review

on:
  issue_comment:
    types: [created]

jobs:
  claude-review:
    # Only run on pull request comments that contain "@claude review"
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '@claude review')
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    
    steps:
      - name: Get PR details
        uses: actions/github-script@v7
        id: pr-details
        with:
          result-encoding: string
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            return pr.data.head.sha;

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr-details.outputs.result }}
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4.1)
          # model: "claude-opus-4-1-20250805"

          # Direct prompt for manual review (triggered by @claude review comment)
          direct_prompt: |
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage
            
            Be constructive and helpful in your feedback.

          # Use sticky comments to update the same comment on subsequent reviews
          use_sticky_comment: true

